// <auto-generated />
namespace MyMVCApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Student_DataAnotation_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_DataAnotation_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201907280822594_Student_DataAnotation_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
